import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
  homeOutline,
  home,
  swapHorizontalOutline,
  swapHorizontal,
  walletOutline,
  wallet,
  flagOutline,
  flag,
  gridOutline,
  grid,
  gitNetworkOutline,
  repeatOutline,
  cardOutline,
  cashOutline,
  trendingUpOutline,
  settingsOutline,
  personCircleOutline,
  logOutOutline,
  chevronForwardOutline,
  addOutline,
  closeOutline,
  checkmarkOutline,
  arrowBackOutline,
  arrowForwardOutline,
  banOutline,
  pencilOutline,
  mailOutline,
  peopleOutline,
  moonOutline,
  sunnyOutline,
  fingerPrintOutline,
  chevronBackOutline,
  ellipseOutline,
  checkmarkCircle,
  alertCircleOutline,
  trashOutline,
} from 'ionicons/icons';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

addIcons({
  'home-outline': homeOutline,
  home,
  'swap-horizontal-outline': swapHorizontalOutline,
  'swap-horizontal': swapHorizontal,
  'wallet-outline': walletOutline,
  wallet,
  'flag-outline': flagOutline,
  flag,
  'grid-outline': gridOutline,
  grid,
  'git-network-outline': gitNetworkOutline,
  'repeat-outline': repeatOutline,
  'card-outline': cardOutline,
  'cash-outline': cashOutline,
  'trending-up-outline': trendingUpOutline,
  'settings-outline': settingsOutline,
  'person-circle-outline': personCircleOutline,
  'log-out-outline': logOutOutline,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-back-outline': chevronBackOutline,
  'add-outline': addOutline,
  'close-outline': closeOutline,
  'trash-outline': trashOutline,
  'checkmark-outline': checkmarkOutline,
  'checkmark-circle': checkmarkCircle,
  'arrow-back-outline': arrowBackOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'ban-outline': banOutline,
  'pencil-outline': pencilOutline,
  'mail-outline': mailOutline,
  'people-outline': peopleOutline,
  'moon-outline': moonOutline,
  'sunny-outline': sunnyOutline,
  'finger-print-outline': fingerPrintOutline,
  'ellipse-outline': ellipseOutline,
  'alert-circle-outline': alertCircleOutline,
});

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err));
